In [8]:
%matplotlib notebook

import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Descomponer una matriz quiere decir que queremos encontrar un producto de matrices que sean iguales a la matriz
# original. Es como descomponer el 6 en 3x2, solo que en lugar de numeros estamos trabajando con matrices

In [3]:
# En la clase anterior vimos como calcular autovalores y autovectores, bueno resulta que esta es una forma de 
# descomponer matrices, llamada descomposicion en autovalores y autovectores. En este caso a la matriz A la 
# descomponemos en sus autovectores y la matriz diagonal de autovalores.

In [4]:
# Retomando la matriz de la clase anterior
A = np.array([[3,2], [4,1]])
print(A)

[[3 2]
 [4 1]]


In [5]:
# calculamos los autovectores y autovalores
autovalores, autovectores = np.linalg.eig(A)

In [7]:
# Y veamos como reconstruimos nuestra matriz original A como producto de los autovalores y autovectores
# Esto es A = V diag(lambda) V_inv
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
print(A_calc)

[[3. 2.]
 [4. 1.]]


In [9]:
# Tenemos otras descomposiciones que tambien son utilizadas
# En el caso de una matriz real simetrica (o sea una matriz simetrica con todos numeros),
# la descomposicion puede ser expresada como A = Q diag(lambda) Q.T

In [10]:
A = np.array([[3,2], [2,3]])
print(A)

[[3 2]
 [2 3]]


In [11]:
# Esta matriz es simetrica
print(A == A.T)

[[ True  True]
 [ True  True]]


In [12]:
# calculamos los autovectores y autovalores
autovalores, autovectores = np.linalg.eig(A)

In [13]:
# Veamos que podemos usar la transpuesta en lugar de la inversa
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
