In [20]:
%matplotlib notebook 

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Ver de graficar las ecuaciones o eliminar la importacion de estas librerias

In [21]:
# Configuracion de los graficos
sns.set()

In [22]:
# Vamos a conocer algunos comandos que nos permitiran generar matrices especiales
# La matriz identidad, es como el 1 en los numeros, multiplicar por el es nuestro no produce efectos.
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
vector = np.array([[2],[3],[5],[7]])
print(vector)                   

[[2]
 [3]
 [5]
 [7]]


In [24]:
v1 = identidad.dot(vector)
print(v1)
#Salvo por el hecho que el formato esta como float ya que la matriz identidad estaba como float, no tuvimos
# modificacion en el vector devuelto

[[2.]
 [3.]
 [5.]
 [7.]]


In [25]:
# Ya tenemos 3 maneras de pensar al contenido de las matrices, ahora agregaremos uno mas, desde mi punto de vista
# el mas importante para Algebra Lineal, pensar a las matrices como Transformaciones lineales
# Pero que es una transformacion lineal? Es una forma de transformar objetos que viven dentro de un espacio
# aplicando ciertas reglas, esas reglas estan expresadas en la matriz
# A medida que avanzamos vamos generando mas preguntas, que es un espacio? lo veremos mas adelante, pero por el
# momento quedemonos con la idea de que aplicar la matriz identidad no transforma el espacio, vimos que 
# multiplicar un vector por la matriz identidad nos devuelve el mismo vector

In [26]:
# Ahora es el turno de la Matriz inversa
# Supongamos que tenemos una matriz A, entones la matriz inversa de A (Ainv) es aquella que cuando hacemos
# A x Ainv nos devuelve la identidad, o sea al ser aplicada deshace la transformacion que habia hecho A al espacio

A = np.array([[1,0,1],[0,1,1],[-1,1,1]])
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [27]:
# Para calcular la inversa de A utilizaremos la funcion linalg.inv()
Ainv = np.linalg.inv(A)
print(Ainv)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [28]:
matriz = A.dot(Ainv)
print(matriz)
#Y vemos que nos devuele la identidad

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# Otro caso especial de matriz es la matriz singular, y son aquellas para las que no existe inversa
singular = np.array([[1,1],[1,1]])
print(singular)

[[1 1]
 [1 1]]


In [30]:
singular_inv = np.linalg.inv(singular)
print(singular_inv)
# La no existencia de inversa para una matriz esta relacionado con que el sistema de ecuaciones que esta 
# representado por esa matriz no tiene solucion o tiene infinitas soluciones, para que la inversa exista
# el sistema debe tener solucion unica. 

LinAlgError: Singular matrix

In [31]:
# La matriz identidad tambien es un ejemplo de una matriz diagonal, esto es una matriz que tiene solo valores en la
# diagonal, o sea todos los valores arriba de la diagonal son 0 y debajo tambien son 0, lo veremos en mas detalle.
vector = np.array([1,2,3])
diag = np.diag(vector)
print(vector)
print(diag)

[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
