In [1]:
import numpy as np

In [15]:
# Escribamos nuevamente nuestros elementos y veamos como funciona el producto interno de una matriz y un vector

escalar = 5.6789
vector = np.array([2,2])
matriz = np.array([[1,2],[3,4],[5,6]])

In [18]:
# Multipliquemos nuestro vector de dimension 2 con la matriz de dimension 3x2 y observemos la diferencia entre
# multiplicar cada elemento de la matriz con cada elemento del vector vs hacer el producto interno

print(vector.shape)
print(matriz.shape)
A = vector * matriz
print(A)

B = matriz.dot(vector)
print(B)

# Vemos que A y B son distintas, A resulto de la misma dimension que la matriz original, mientras que B que es
# el resultado del producto interno o punto tiene la primer dimension del objeto a la izquierda del producto interno
# y la segunda dimension del que esta a la derecha, teniendo esto en cuenta siempre podremos validar si el
# resultado que estamos obteniendo tiene las dimensiones esperadas

print(A.shape)
print(B.shape)

(2,)
(3, 2)
[[ 2  4]
 [ 6  8]
 [10 12]]
[ 6 14 22]
(3, 2)
(3,)


In [19]:
# Tenemos dos maneras de usar la funcion .dot
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)
# Y ambas devuelven el mismo resultado

[ 6 14 22]
[ 6 14 22]


In [20]:
# Escribamos nuevos objetos y veamos como funciona el producto interno entre 2 matrices

A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [21]:
C = A.dot(B)
print(A.shape)
print(B.shape)
print(C.shape)
print(C)

(4, 3)
(3, 2)
(4, 2)
[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]


In [22]:
# Describir como es el producto interno en caso de encontrarlo util