In [1]:
import numpy as np

In [6]:
# Escribamos nuevos objetos y veamos como funciona el producto interno entre 2 matrices

A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(2, 2)
(2, 2)


In [7]:
# Queremos ver si el producto interno es asociativo o sea si Ax(BxC) = (AxB)xC
# De esto existen pruebas formales en matematica, pero nosotros vamos a tomarlo por cierto si funciona con
# nuestro ejemplo
D = A.dot(B.dot(C))
print(D)

[[ 60  26]
 [145  63]
 [295 129]]


In [8]:
E = (A.dot(B)).dot(C)
print(E)

[[ 60  26]
 [145  63]
 [295 129]]


In [9]:
# Resulta que realizar las operaciones de estas dos formas da el mismo resultado 
print(D==E)


[[ True  True]
 [ True  True]
 [ True  True]]


In [10]:
# Queremos ver si el producto interno es distributivo o sea si Ax(B+C) = (AxB)+(AxC)
# Necesitamos otras matrices para que las operaciones esten bien definidas
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1],[2]])
C = np.array([[3],[4]])

print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(2, 1)
(2, 1)


In [11]:
# Veamos si tambien verificamos que es distributivo el producto interno
D = A.dot(B+C)
print(D)

[[ 26]
 [ 62]
 [122]]


In [12]:
E = A.dot(B) + A.dot(C)
print(E)

[[ 26]
 [ 62]
 [122]]


In [13]:
# Resulta que realizar las operaciones de estas dos formas da el mismo resultado 
print(D==E)

[[ True]
 [ True]
 [ True]]


In [14]:
# Pero NO es conmutativa, no podemos intercambiar el orden ya que BxC != CxB
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

print(B.shape)
print(C.shape)

(2, 2)
(2, 2)


In [16]:
D = B.dot(C)
E = C.dot(B)
print(D)
print(E)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]


In [17]:
print(D==E)
#Vemos que si cambiamos el orden dan un resultado distinto

[[False False]
 [False False]]


In [21]:
# Vale la pena tener en cuenta que la multiplicacion de vectores si es conmutativa, o sea v1_t x v2 = v2_t x v1
v1 = np.array([[2],[7]])
v2 = np.array([[5],[3]])
print(v1)
print(v2)

[[2]
 [7]]
[[5]
 [3]]


In [22]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)
print(v1_tv2)
print(v2_tv1)

[[31]]
[[31]]
